export class Company {
    constructor(
        public nid: number,
        public title: string,
        public description: string,
        public city: string,
        public logo: string
    ) {}    
}
    export const COMPANIES: Company[] = [
        {"nid":69,"title":"Leuschke Group","description":"Eget nunc lobortis mattis aliquam faucibus purus in. Enim lobortis scelerisque fermentum dui faucibus. Dolor morbi non arcu risus quis varius. Arcu felis bibendum ut tristique et. Nam aliquam sem et tortor consequat id porta nibh venenatis. Viverra accumsan in nisl nisi. Tempor id eu nisl nunc mi ipsum faucibus. Leo in vitae turpis massa sed. Viverra accumsan in nisl nisi. Leo urna molestie at elementum eu facilisis. Commodo elit at imperdiet dui accumsan sit amet nulla facilisi. Viverra suspendisse potenti nullam ac tortor vitae. Vitae proin sagittis nisl rhoncus mattis rhoncus urna. Sed adipiscing diam donec adipiscing tristique risus nec feugiat. Nunc aliquet bibendum enim facilisis gravida neque. Nunc eget lorem dolor sed. Fames ac turpis egestas sed tempus. Tellus mauris a diam maecenas sed enim ut sem. In egestas erat imperdiet sed euismod nisi porta lorem. Proin sed libero enim sed faucibus.","city":"New Marleeside","logo":"\/sites\/default\/files\/2019-11\/758-l.png"},
        {"nid":68,"title":"Kovacek LLC","description":"Proin fermentum leo vel orci porta non pulvinar neque laoreet. Est lorem ipsum dolor sit amet consectetur adipiscing. Scelerisque varius morbi enim nunc faucibus a. At consectetur lorem donec massa sapien faucibus et molestie. Risus at ultrices mi tempus. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit aliquam. At auctor urna nunc id cursus metus aliquam eleifend mi. Turpis egestas sed tempus urna. Imperdiet proin fermentum leo vel orci porta non. Aliquet risus feugiat in ante metus dictum at. Feugiat nisl pretium fusce id velit ut. Quis risus sed vulputate odio ut enim blandit. Vel quam elementum pulvinar etiam non quam. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna. Auctor augue mauris augue neque gravida.","city":"Medhurstburgh","logo":"\/sites\/default\/files\/2019-11\/random_logo_1.png"},
        {"nid":67,"title":"Waelchi and Sons","description":"Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Lorem sed risus ultricies tristique nulla. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Faucibus purus in massa tempor nec feugiat nisl. Fusce ut placerat orci nulla pellentesque dignissim enim sit amet. Nunc sed id semper risus in hendrerit. Pretium vulputate sapien nec sagittis aliquam. Aliquam sem et tortor consequat id porta nibh. Aliquam vestibulum morbi blandit cursus risus at ultrices. Elit duis tristique sollicitudin nibh. Pellentesque nec nam aliquam sem et tortor. Ultricies integer quis auctor elit sed vulputate mi sit. Orci porta non pulvinar neque laoreet suspendisse interdum. Imperdiet proin fermentum leo vel. In fermentum et sollicitudin ac orci phasellus egestas. Sed euismod nisi porta lorem mollis aliquam. Sit amet venenatis urna cursus eget nunc.","city":"West Wall","logo":"\/sites\/default\/files\/2019-11\/12affc8078-450.png"}]
    
